query business($id: String!) {
  user(__id: $id) {
    id
    __id
    name
    username
    avatar
    phone
    email
    verified
    bio
    created_at
    reviews {
      id
      rating
      review
      business {
        id
        __id
        business_name
        address
      }
    }
  }
}
